export const LOCAL_STORAGE_THEME = "theme";
export const LOCAL_STORAGE_TOKEN = "token";
export const LOCAL_STORAGE_REFRESH = "refreshToken";
export const DEBOUNCE_TIME = 500;
export const MESSAGE_TIMER = 3000;
export const LOGIN_REJECTED = "user/loginUser/rejected";
export const REGISTER_REJECTED = "user/registerUser/rejected";
export const TOKEN_EXPIRED_STATUS = 401;
export const TOKEN_EXPIRED_MESSAGE = "Token expired";
